version: '3.9'

services:
  nextjs_supa_stripe:
    build: .
    ports:
      - "3000:3000"
    networks: 
      - next_supa
    environment:
      - NEXT_PUBLIC_SITE_URL="http://localhost:3000"

        # These environment variables are used for Supabase Local Dev
      - NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
      - NEXT_PUBLIC_SUPABASE_URL="http://host.docker.internal:8000"
      - SUPABASE_SERVICE_ROLE_KEY=

      # Get these from Stripe dashboard
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
      - STRIPE_SECRET_KEY=
      - STRIPE_WEBHOOK_SECRET=

      # Set an environment variable
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NO_UPDATE_NOTIFIER=true
    volumes:
      - "./app:/next-app/app"
      - "./utils:/next-app/utils"
      - "./public:/next-app/public"
      - "./styles:/next-app/styles"

networks:
  next_supa:
    external: true

